# Code generated by protoc-gen-liquibase. DO NOT EDIT.
FROM liquibase/liquibase:4.27.0
COPY update_sql.sh /entry.sh
COPY mysql-connector-8.0.28.jar /mysql-connector-8.0.28.jar
ENTRYPOINT ["/entry.sh"]
